/**
 *
 * @author Tanjilul Anwar
 */
package gui;


import java.io.*;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.*;


public class NewJFrame4 extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
    
    
    public static String idc;//brings id from login
    
    public NewJFrame4() {
       
        initComponents();
    }
    
    
    public void connect()
    {
     
    DefaultListModel model1 = new DefaultListModel();
    File o = new File("E:"+File.separator + "server"+File.separator +idc);
    File[] yourFileList = o.listFiles();
    for(File f : yourFileList) {
    model1.addElement(f.getName());
    }
    jList1.setModel(model1);     

    }
    public void close() { 
    this.setVisible(false);
    this.dispose();
}
    public void copier(File x,File y ) throws FileNotFoundException, IOException
    {
        BufferedOutputStream bos;
        try (BufferedInputStream bis = new BufferedInputStream(new FileInputStream(x))) {
            bos = new BufferedOutputStream(new FileOutputStream(y));
            int theByte;
            while((theByte = bis.read()) != -1)
            {
                bos.write(theByte);}
        }
                bos.close();
    }
    
    
    
    public void upload()
    {
        
    JFileChooser jFileChooser = new JFileChooser();
    int status = jFileChooser.showOpenDialog(null);
    
    if (status == JFileChooser.APPROVE_OPTION) {
    File nFile =jFileChooser.getSelectedFile();
    String selectedFilePath = jFileChooser.getSelectedFile().getAbsolutePath();
    
    File sourceFile = new File(selectedFilePath);
    File destinationFile = new File("E:"+File.separator + "server"+File.separator +idc +File.separator+ nFile.getName());
    Path sourcePath = sourceFile.toPath();
    Path destinationPath = destinationFile.toPath();
    try {
       // Files.copy(sourcePath, destinationPath);
       if(destinationFile.exists() && !destinationFile.isDirectory()){
        JOptionPane.showMessageDialog(this, "Use the update option to upload the same file");
       }
       else{
                copier(sourceFile,destinationFile);
                connect();    
            JOptionPane.showMessageDialog(this, nFile.getName()+" has been uploaded!");}

    } 
    catch (IOException ex) {
        Logger.getLogger(NewJFrame4.class.getName()).log(Level.SEVERE, null, ex);
    }
}
    
    }
    
    
    public void delete(){
    
    DefaultListModel model = (DefaultListModel) jList1.getModel();
    String filex = jList1.getSelectedValue();
    File fl = new File("E:"+File.separator + "server"+File.separator +idc +File.separator+ filex);

    JDialog.setDefaultLookAndFeelDecorated(true);
    int res = JOptionPane.showConfirmDialog(this," delete "+filex+ "?","confirm",JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
 
    if (res == JOptionPane.YES_OPTION){
      if(fl.delete()){
      model.removeElement(filex);
      JOptionPane.showMessageDialog(this, filex+" deleted!");
     }
     else{JOptionPane.showMessageDialog(this, "Can't delete "+filex);}}
 else{
        //do nothing when pressed no
    }
      
     }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(0, 204, 204));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Now with premium ssd hosting");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 490, -1, -1));

        jList1.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "*press connect to enter your directory", "", "", "" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(jList1);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 460, 350));

        jPanel2.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 70, 480, 360));

        jPanel3.setBackground(new java.awt.Color(0, 204, 204));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("RKLUL47");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Fastest, efficient and reliable");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jLabel1))
                .addContainerGap(501, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addContainerGap())
        );

        jPanel2.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 690, 70));

        jButton1.setBackground(new java.awt.Color(0, 153, 153));
        jButton1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Connect");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 110, 90, 30));

        jButton2.setBackground(new java.awt.Color(204, 51, 0));
        jButton2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("Delete");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 460, 80, 30));

        jButton3.setBackground(new java.awt.Color(0, 153, 153));
        jButton3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.setText("Log out");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 470, 90, 30));

        jButton4.setBackground(new java.awt.Color(0, 153, 153));
        jButton4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton4.setForeground(new java.awt.Color(255, 255, 255));
        jButton4.setText("Upload");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 160, 90, 30));

        jButton5.setBackground(new java.awt.Color(0, 153, 153));
        jButton5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton5.setForeground(new java.awt.Color(255, 255, 255));
        jButton5.setText("Download");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 200, 110, 30));

        jButton6.setBackground(new java.awt.Color(0, 153, 153));
        jButton6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton6.setForeground(new java.awt.Color(255, 255, 255));
        jButton6.setText("Update");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 270, 90, 30));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(-4, 0, 690, 520));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
    JFileChooser jFileChooser = new JFileChooser();
    int status = jFileChooser.showOpenDialog(null);
    
    if (status == JFileChooser.APPROVE_OPTION) {
    File nFile =jFileChooser.getSelectedFile();
    String selectedFilePath = jFileChooser.getSelectedFile().getAbsolutePath();
    
    File sourceFile = new File(selectedFilePath);
    File destinationFile = new File("E:"+File.separator + "server"+File.separator +idc +File.separator+ nFile.getName());
    Path sourcePath = sourceFile.toPath();
    Path destinationPath = destinationFile.toPath();
    try {
       // Files.copy(sourcePath, destinationPath);
       if(destinationFile.exists() && !destinationFile.isDirectory()) { 
       JDialog.setDefaultLookAndFeelDecorated(true);
    int res = JOptionPane.showConfirmDialog(this," do you wish to keep the older file?","confirm",JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
 
    if (res == JOptionPane.YES_OPTION){
        String g = JOptionPane.showInputDialog("Rename new file:",nFile.getName());
             destinationFile = new File("E:"+File.separator + "server"+File.separator +idc +File.separator+ g);   
             copier(sourceFile,destinationFile);
               connect();  
               JOptionPane.showMessageDialog(this, "File saved!");
      }
    else if(res == JOptionPane.NO_OPTION){
       
        copier(sourceFile,destinationFile);
        connect();
      JOptionPane.showMessageDialog(this, "File Replaced!");

    } // do something
}
       else
       {      
            JOptionPane.showMessageDialog(this," choose a file to update or go to upload option!");}

    } 
    catch (IOException ex) {
        Logger.getLogger(NewJFrame4.class.getName()).log(Level.SEVERE, null, ex);
    }
}
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed

        DefaultListModel model = (DefaultListModel) jList1.getModel();
        String filex = jList1.getSelectedValue();
        File h = new File("E:"+File.separator + "server"+File.separator +idc +File.separator+ filex);

        JFileChooser chooser = new JFileChooser(){
            public void approveSelection() {
                if (getSelectedFile().isFile()) {
                    return;
                }

                else
                super.approveSelection();
            }
        };
        chooser.setFileSelectionMode( JFileChooser.FILES_AND_DIRECTORIES );
        chooser.setSelectedFile(new File(filex));
        int status = chooser.showSaveDialog(null);
        if (status == JFileChooser.APPROVE_OPTION  ) {
            File nFile =chooser.getSelectedFile();
            String selectedFilePath = chooser.getSelectedFile().getAbsolutePath();

            File destinationFile = new File(selectedFilePath );

            File sourceFile = new File("E:"+File.separator + "server"+File.separator +idc +File.separator+ h.getName());

            Path sourcePath = sourceFile.toPath();
            Path destinationPath = destinationFile.toPath();

            try {
                //Files.copy(sourcePath, destinationPath);
                copier(sourceFile,destinationFile);

                connect();
                JOptionPane.showMessageDialog(this, filex+" download complete!");

            } catch (IOException ex) {

                Logger.getLogger(NewJFrame4.class.getName()).log(Level.SEVERE, null, ex);
            }
        }

    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        upload();
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        NewJFrame1 obj= new NewJFrame1();

        obj.setVisible(true);        // goes to login page
        close();        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    @SuppressWarnings("empty-statement")
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        delete();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        connect();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewJFrame4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewJFrame4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewJFrame4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewJFrame4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
    
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewJFrame4().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JList<String> jList1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
